import { StyleSheet } from "react-native";
import { colors, fonts } from "../constants/theme";

export const globalStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 36,
    gap: 20,
  },
  header: {
    gap: 12,
  },
  eyebrow: {
    color: colors.brandSoft,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
  },
  title: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 35,
    lineHeight: 40,
    fontWeight: "800",
  },
  subtitle: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 24,
  },
  heroSection: {
    gap: 16,
  },
  heroImage: {
    minHeight: 390,
    borderRadius: 30,
    overflow: "hidden",
    justifyContent: "space-between",
    padding: 20,
  },
  heroImageInner: {
    borderRadius: 30,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  heroTopRow: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    zIndex: 1,
  },
  heroTag: {
    backgroundColor: colors.brand,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroTagText: {
    color: colors.background,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "800",
  },
  heroTagDark: {
    backgroundColor: "rgba(8, 16, 21, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.16)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroTagDarkText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 13,
    fontWeight: "700",
  },
  heroContent: {
    zIndex: 1,
    gap: 16,
  },
  heroTextBlock: {
    gap: 8,
  },
  heroLabel: {
    color: colors.brandSoft,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  heroTitle: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 31,
    lineHeight: 34,
    fontWeight: "800",
  },
  heroMeta: {
    color: colors.textSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    fontWeight: "700",
  },
  heroDescription: {
    color: colors.textSoft,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 24,
  },
  heroPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
  },
  inlineSignal: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(8, 16, 21, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  inlineSignalDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.success,
  },
  inlineSignalText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
  },
  arrivalRow: {
    zIndex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  arrivalChip: {
    minWidth: 100,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(8, 16, 21, 0.76)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
    gap: 4,
  },
  arrivalLabel: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  arrivalValue: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 20,
    fontWeight: "800",
  },
  commandDeck: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.outlineStrong,
    padding: 20,
    gap: 16,
  },
  commandHeader: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
  },
  commandBadge: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "rgba(240, 68, 68, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(240, 68, 68, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  commandBadgeText: {
    color: colors.dangerSoft,
    fontFamily: fonts.display,
    fontSize: 17,
    fontWeight: "800",
  },
  commandTextBlock: {
    flex: 1,
    gap: 6,
  },
  commandEyebrow: {
    color: colors.dangerSoft,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  commandTitle: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
  },
  commandDescription: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  alertButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: colors.route,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  alertButtonIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: colors.routeDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  alertButtonIconText: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 26,
    lineHeight: 28,
    fontWeight: "800",
  },
  alertButtonCopy: {
    flex: 1,
    gap: 4,
  },
  alertButtonTitle: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 22,
    fontWeight: "800",
  },
  alertButtonText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  commandMetaRow: {
    gap: 10,
  },
  commandMetaCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.outline,
    padding: 14,
    gap: 6,
  },
  commandMetaLabel: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  commandMetaValue: {
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "700",
  },
  dispatchCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outline,
    borderRadius: 20,
    padding: 16,
    gap: 6,
  },
  dispatchLabel: {
    color: colors.brandSoft,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  dispatchTitle: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 18,
    fontWeight: "800",
  },
  dispatchText: {
    color: colors.textSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  dispatchMeta: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  metricsRow: {
    gap: 12,
  },
  operationGrid: {
    gap: 12,
  },
  operationCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.outline,
    padding: 16,
    gap: 6,
  },
  operationLabel: {
    color: colors.brandSoft,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  operationValue: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "800",
  },
  operationText: {
    color: colors.textSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  routeBar: {
    flexDirection: "row",
    gap: 14,
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.outline,
    padding: 16,
    alignItems: "center",
  },
  routeIndicator: {
    width: 12,
    alignSelf: "stretch",
    borderRadius: 999,
    backgroundColor: colors.route,
  },
  routeCopy: {
    flex: 1,
    gap: 6,
  },
  routeTitle: {
    color: colors.text,
    fontFamily: fonts.display,
    fontSize: 19,
    fontWeight: "800",
  },
  routeText: {
    color: colors.textSoft,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  alertList: {
    gap: 12,
  },
  chatList: {
    gap: 12,
  },
  chatComposer: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: colors.surfaceStrong,
    borderTopWidth: 1,
    borderTopColor: colors.outlineStrong,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  chatInput: {
    flex: 1,
    minHeight: 54,
    maxHeight: 140,
    backgroundColor: colors.surfaceLifted,
    borderWidth: 1,
    borderColor: colors.outlineStrong,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 14,
    textAlignVertical: "top",
  },
  chatButton: {
    minWidth: 110,
    height: 54,
    borderRadius: 18,
    backgroundColor: colors.brand,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  chatButtonText: {
    color: colors.background,
    fontFamily: fonts.body,
    fontSize: 14,
    fontWeight: "800",
  },
  noticeList: {
    gap: 12,
  },
  
  
});